version: '2'
services:
  web:
    image: nginx
    volumes:
      - ./web/index.html:/usr/share/nginx/html/index.html
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
  prerender:
    build: ./prerender
    ports:
      - "3000:80"
